language:
  - cpp
compiler:
  - gcc

env:
  global:
    - ROS_DISTRO=hydro
#    - ROS_DISTRO=indigo


before_install: 
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - codename=`cat /etc/lsb-release | grep -m 1 "DISTRIB_CODENAME=" | cut -d "=" -f2`
  - sudo sh -c "echo 'deb http://packages.ros.org/ros/ubuntu $codename main' > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update

install:
  - sudo apt-get install gazebo ros-$ROS_DISTRO-gazebo-ros-control ros-$ROS_DISTRO-ros-control ros-$ROS_DISTRO-effort-controllers ros-$ROS_DISTRO-joint-state-controller ros-$ROS_DISTRO-joint-trajectory-controller ros-$ROS_DISTRO-joint-trajectory-action
before_script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - mkdir -p ~/catkin_ws/src
  - export REPOSITORY_NAME=${PWD##*/}
  - ln -s $(pwd) ~/catkin_ws/src/$REPOSITORY_NAME
  - cd ~/catkin_ws/src
  - catkin_init_workspace

script:
  - cd ~/catkin_ws/
  - catkin_make
